name: Build and Publish

permissions:
  actions: write

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'
      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew
      - name: Install dependencies
        run: ./gradlew dependencies
      - name: Publish
        run: ./gradlew publish
        env: 
          MAVEN_URL: ${{ secrets.REPO_PUBLISH_URL }}
          MAVEN_USERNAME: ${{ secrets.REPO_PUBLISH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.REPO_PUBLISH_TOKEN }}
